# Generated by Django 5.2.15 on 2026-06-15 11:05

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_auto_20250904_1125"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClasseGroupModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("label", models.CharField(max_length=120)),
                (
                    "teaching",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.teachingmodel"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScholarYearModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("label", models.CharField(max_length=9)),
                ("date_start", models.DateField()),
                ("date_end", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="StudentLevelCourseModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentLevelModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="classemodel",
            name="channel",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="classemodel",
            name="form",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="classemodel",
            name="orientation",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="givencoursemodel",
            name="hours_per_week",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="classemodel",
            name="year",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AddField(
            model_name="classemodel",
            name="classe_group",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="core.classegroupmodel"
            ),
        ),
        migrations.AddConstraint(
            model_name="classemodel",
            constraint=models.UniqueConstraint(
                fields=("year", "letter", "classe_group", "teaching"), name="unique_classe"
            ),
        ),
        migrations.AddConstraint(
            model_name="scholaryearmodel",
            constraint=models.UniqueConstraint(
                models.F("label"), name="unique_label_for_scholar_year"
            ),
        ),
        migrations.AddField(
            model_name="givencoursemodel",
            name="scholar_year",
            field=models.ForeignKey(
                default=core.models.GivenCourseModel.get_current_scholar_year,
                on_delete=django.db.models.deletion.RESTRICT,
                to="core.scholaryearmodel",
            ),
        ),
        migrations.AddField(
            model_name="studentlevelcoursemodel",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.givencoursemodel"
            ),
        ),
        migrations.AddField(
            model_name="studentlevelmodel",
            name="classe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.classemodel"
            ),
        ),
        migrations.AddField(
            model_name="studentlevelmodel",
            name="scholar_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.scholaryearmodel"
            ),
        ),
        migrations.AddField(
            model_name="studentlevelmodel",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.studentmodel"
            ),
        ),
        migrations.AddField(
            model_name="studentlevelcoursemodel",
            name="student_level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.studentlevelmodel"
            ),
        ),
        migrations.AddConstraint(
            model_name="studentlevelmodel",
            constraint=models.UniqueConstraint(
                fields=("student", "classe", "scholar_year"), name="unique_student_level"
            ),
        ),
    ]
