# Generated by Django 5.2.15 on 2026-06-18 09:35

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_classegroupmodel_scholaryearmodel_studentlevelcourse_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="scholaryearmodel",
            name="unique_label_for_scholar_year",
        ),
        migrations.AddField(
            model_name="studentlevelcoursemodel",
            name="date_end",
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name="studentlevelcoursemodel",
            name="date_start",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="studentlevelmodel",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.studentmodel"
            ),
        ),
        migrations.AddConstraint(
            model_name="scholaryearmodel",
            constraint=models.UniqueConstraint(models.F("label"), name="unique_label_scolar_year"),
        ),
    ]
