# Generated by Django 5.2.15 on 2026-06-15 11:06

from cProfile import label

from django.db import migrations
from django.db.models import ObjectDoesNotExist

from core.utilities import get_scholar_year


def migrate(apps, schema_editor):
    StudentModel = apps.get_model("core", "StudentModel")
    ClasseModel = apps.get_model("core", "ClasseModel")
    ScholarYearModel = apps.get_model("core", "ScholarYearModel")
    ClasseGroupModel = apps.get_model("core", "ClasseGroupModel")
    StudentLevelModel = apps.get_model("core", "StudentLevelModel")
    StudentLevelCourseModel = apps.get_model("core", "StudentLevelCourseModel")

    # Create a new ScholarYearModel.
    current_scholar_year = get_scholar_year()
    try:
        scholar_year = ScholarYearModel.objects.get(label__startswith=str(current_scholar_year))
    except ObjectDoesNotExist:
        core_settings = CoreSettingsModel.objects.all().first()
        date_start = f"{current_scholar_year}-{core_settings.month_scholar_year_start}-{core_settings.day_scholar_year_start}"
        date_end = f"{current_scholar_year + 1}-{core_settings.month_scholar_year_start}-{core_settings.day_scholar_year_start - 1}"
        scholar_year = ScholarYearModel(
            label=f"{scholar_year}-{scholar_year+1}", date_start=date_start, date_end=date_end
        )
        scholar_year.save()

    # Create class groups and update classe model.
    for classe in ClasseModel.objects.all():
        label = f"{classe.year}ème année" if classe.year > 1 else "1ère année"
        classe_group, _ = ClasseGroupModel.objects.get_or_create(
            label=label, teaching=classe.teaching
        )
        classe.classe_group = classe_group

    # Create Student Level and student level course models.
    for student in StudentModel.objects.filter(classe__isnull=False):
        student_level = StudentLevelModel.objects.create(
            student=student, classe=student.classe, scholar_year=scholar_year
        )
        for given_courses in student.courses.all():
            StudentLevelCourseModel.objects.create(
                student_level=student_level,
                course=given_courses,
                date_start=date_start,
                date_end=date_end,
            )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_remove_scholaryearmodel_unique_label_for_scholar_year_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate, reverse_code=migrations.RunPython.noop),
    ]
