# Generated by Django 5.2.15 on 2026-06-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_auto_20260615_1306"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="scholaryearmodel",
            name="unique_label_scolar_year",
        ),
        migrations.AlterField(
            model_name="scholaryearmodel",
            name="label",
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
