# Generated by Django 4.2.16 on 2024-11-25 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0019_auto_20220524_1007"),
    ]

    operations = [
        migrations.CreateModel(
            name="Classe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("classe", models.PositiveSmallIntegerField()),
                ("letter", models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name="ClasseGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("studyYear", models.PositiveSmallIntegerField()),
                ("title", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="Cotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField()),
                ("max_note", models.IntegerField()),
                ("madeDate", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("hoursPerWeek", models.IntegerField(verbose_name="hoursPerWeek")),
            ],
        ),
        migrations.CreateModel(
            name="ScholarYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("label", models.CharField(max_length=9)),
                ("dateStart", models.DateField()),
                ("dateEnd", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="StudentLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "classe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="report.classe"
                    ),
                ),
                (
                    "scholarYear",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="report.scholaryear"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.studentmodel"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentLevelCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="report.course"
                    ),
                ),
                (
                    "studentLevel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="report.studentlevel"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Period",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("periodNum", models.PositiveSmallIntegerField()),
                ("dateStart", models.DateField()),
                ("dateEnd", models.DateField()),
                (
                    "scholarYear",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="report.scholaryear"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("note", models.IntegerField(default=0)),
                ("comment", models.CharField()),
                (
                    "cotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="report.cotation"
                    ),
                ),
                (
                    "studentLevel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="report.studentlevel"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="course",
            name="scholarYear",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="report.scholaryear"
            ),
        ),
        migrations.AddField(
            model_name="cotation",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="report.course"
            ),
        ),
    ]
