# Generated by Django 4.2.16 on 2025-01-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='scholaryear',
            constraint=models.UniqueConstraint(models.F('label'), name='unique_label'),
        ),
    ]
