# Generated by Django 4.2.18 on 2026-01-12 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0002_scholaryear_unique_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="classe",
            name="classeGroup",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to="report.classegroup"
            ),
        ),
        migrations.AddField(
            model_name="scholaryear",
            name="classeGroup",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to="report.classegroup"
            ),
        ),
    ]
