# Generated by Django 4.2.18 on 2026-01-12 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0003_classe_classegroup_scholaryear_classegroup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classe",
            name="classeGroup",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="report.classegroup"
            ),
        ),
        migrations.AlterField(
            model_name="scholaryear",
            name="classeGroup",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="report.classegroup"
            ),
        ),
    ]
