# Generated by Django 4.2.18 on 2026-01-12 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0004_alter_classe_classegroup_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scholaryear",
            name="classeGroup",
        ),
        migrations.AddField(
            model_name="period",
            name="classeGroup",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="report.classegroup"
            ),
        ),
    ]
