# Generated by Django 5.2.15 on 2026-06-18 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_remove_scholaryearmodel_unique_label_for_scholar_year_and_more"),
        ("report", "0005_remove_scholaryear_classegroup_period_classegroup"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Cotation",
            new_name="CotationModel",
        ),
        migrations.RenameModel(
            old_name="Note",
            new_name="NoteModel",
        ),
        migrations.RenameModel(
            old_name="Period",
            new_name="PeriodModel",
        ),
        migrations.RemoveField(
            model_name="classe",
            name="classeGroup",
        ),
        migrations.RemoveField(
            model_name="studentlevel",
            name="classe",
        ),
        migrations.RemoveField(
            model_name="course",
            name="scholarYear",
        ),
        migrations.RemoveField(
            model_name="studentlevelcourse",
            name="course",
        ),
        migrations.RemoveField(
            model_name="studentlevel",
            name="scholarYear",
        ),
        migrations.RemoveField(
            model_name="studentlevel",
            name="student",
        ),
        migrations.RemoveField(
            model_name="studentlevelcourse",
            name="studentLevel",
        ),
        migrations.RenameField(
            model_name="cotationmodel",
            old_name="madeDate",
            new_name="made_date",
        ),
        migrations.RenameField(
            model_name="periodmodel",
            old_name="dateEnd",
            new_name="date_end",
        ),
        migrations.RenameField(
            model_name="periodmodel",
            old_name="dateStart",
            new_name="date_start",
        ),
        migrations.RenameField(
            model_name="periodmodel",
            old_name="periodNum",
            new_name="period_num",
        ),
        migrations.RemoveField(
            model_name="notemodel",
            name="studentLevel",
        ),
        migrations.RemoveField(
            model_name="periodmodel",
            name="classeGroup",
        ),
        migrations.RemoveField(
            model_name="periodmodel",
            name="scholarYear",
        ),
        migrations.AddField(
            model_name="notemodel",
            name="student_level",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.studentlevelmodel",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="periodmodel",
            name="classe_group",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="core.classegroupmodel"
            ),
        ),
        migrations.AddField(
            model_name="periodmodel",
            name="scholar_year",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.scholaryearmodel",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cotationmodel",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.givencoursemodel"
            ),
        ),
        migrations.AddConstraint(
            model_name="periodmodel",
            constraint=models.UniqueConstraint(
                fields=("period_num", "classe_group", "scholar_year"),
                name="unique_period",
                violation_error_message="Cette periode existe déjà",
            ),
        ),
        migrations.DeleteModel(
            name="ClasseGroup",
        ),
        migrations.DeleteModel(
            name="Classe",
        ),
        migrations.DeleteModel(
            name="Course",
        ),
        migrations.DeleteModel(
            name="ScholarYear",
        ),
        migrations.DeleteModel(
            name="StudentLevel",
        ),
        migrations.DeleteModel(
            name="StudentLevelCourse",
        ),
    ]
