# Generated by Django 5.2.15 on 2026-06-22 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_remove_scholaryearmodel_unique_label_scolar_year_and_more"),
        ("report", "0006_rename_cotation_cotationmodel_rename_note_notemodel_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="periodmodel",
            name="unique_period",
        ),
        migrations.RemoveField(
            model_name="periodmodel",
            name="period_num",
        ),
        migrations.AddField(
            model_name="periodmodel",
            name="period_label",
            field=models.CharField(default="P", max_length=200),
        ),
        migrations.AlterField(
            model_name="periodmodel",
            name="classe_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.classegroupmodel"
            ),
        ),
        migrations.AddConstraint(
            model_name="periodmodel",
            constraint=models.UniqueConstraint(
                fields=("period_label", "classe_group", "scholar_year"),
                name="unique_period",
                violation_error_message="Cette periode existe déjà",
            ),
        ),
    ]
