# Generated by Django 5.2.15 on 2026-06-22 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0007_remove_periodmodel_unique_period_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cotationmodel",
            old_name="course",
            new_name="given_course",
        ),
    ]
