# Generated by Django 5.2.15 on 2026-07-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0008_rename_course_cotationmodel_given_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cotationmodel",
            name="max_note",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="notemodel",
            name="note",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
